[dependencies]
ndarray = '0.13.0'
sprs = '0.6.5'


[dependencies.fitsimg]
git = 'https://github.com/astrojhgu/rust_fitsimg.git'

[package]
authors = ['Gu Junhua <jhgu@nao.cas.cn>']
edition = '2018'
name = 'simscan'
version = '0.1.0'
